### PR TITLE
[#2220] Add Den Haag File component in OIP

### LINKED ISSUE #2220: Get File component through 'Help Wanted' stage
## Background

The 'File' component will need to go through the very first 'Help wanted' phase, and after the NLDS core team approves it, it will become available on:
https://nldesignsystem.nl/file
As well as in the NLDS Themes Storybook repository
https://nl-design-system.github.io/themes/?path=/story/denhaag-file--den-haag-theme

Currently it is not yet officially through the Help wanted phase:
https://github.com/orgs/nl-design-system/projects/55/views/1?filterQuery=file

Image
 
---

## Action in NLDS

Getting it through all of the NLDS 'Help wanted' steps will be a PR in the DenHaag NLDS repository, not OIP.
Jiro's PR for 'Help Wanted' is in progress here: https://github.com/nl-design-system/themes/pull/1353

---

## Effect on OIP

Additionally: We can also speed up the process of "getting it through Community stage" (the next phase) by implementing it in Open Inwoner itself.

> "...handige volgende stap voor file component kan zijn om die alvast in OIP uit te proberen (de den haag community versie). Wat jij tegen komt als mogelijke issues helpen dan al meteen voor de community fase..."

For OIP we can partially use the DenHaag CSS structure and styling. With OIP's Preact component (we use: custom Material Icons instead of SVG, OIP has delete button functionality , web-component wrapper, etc.) we can then contribute to NLDS.

---

## TODO

- [x] make PR in NLDS Themes directory to add the File Storybook stories + regressions tests
- [x] add and use the File component in OIP in both OIP Storybook and Production
- [x] inventarisation of next steps (Mijn Services board?)

---

### Additional info 

Community steps:
https://nldesignsystem.nl/handboek/estafettemodel/componenten/community/voor-organisaties/ 

Next 'Candidate' stage: "Wanneer tenminste twéé organisaties in de community een component van elkaar hergebruiken "in productie", en de component beide keren een positieve toegankelijkheidsverklaring krijgt of alle geconstateerde problemen nadien zijn verholpen, wordt het een kandidaat om op te nemen in de officiële verzameling."

### PR DESCRIPTION
**Pull request by jiromaykin**
## Summary

Adding the component in the Samenwerken detail page http://localhost:8000/samenwerken/....
Also in Acties from the Profiel page: http://localhost:8000/mijn-profiel/actions/ (collapse accordeon to see any files.
And in de "Bekijk voorstel" pop-up modal if the template contains a File: http://localhost:8000/samenwerken/choose-template/

---

Screenshot 2026-03-03 at 19 12 06

---

Differences between OIP implementation and `denhaag` version, so Den Haag needs to know:

Wat OIP van Den Haag File component gebruikt:

- CSS/HTML classes en styling (.denhaag-file, .denhaag-file__left, etc.)

Wat OIP zelf heeft gebouwd:

1. van de hele File bar een Div gemaakt in plaats van een link (beter voor schermlezers en specifiekere feedback op de download/delete functies)
2. specifieke styling voor de download-link toegevoegd (text-decoration none)
3. Preact component wrapper / Web-component integratie
4. Custom Material Icons (in plaats van SVG)
5. Delete button met eigen functionaliteit en styling toevoegen en/of overschrijven (`.denhaag-link--remove` border weghalen)
6. Variant zonder delete of download functie, alleen bedoeld voor preview (bij kiezen voor Samenwerkings plan sjabloon)
7. showDelete en showDownload flags
8. styling voor de uppercase file extensie en bestandsgrootte
9. missende design token voor border-radius van het hele File component.

## NLDS specific procedures

The 'File' component will need to go through the very first 'Help wanted' phase, and after the NLDS core team appoves it, it will later become available on:
https://nldesignsystem.nl/file
Currently it is not yet officially part of the Help wanted phase:
https://github.com/orgs/nl-design-system/projects/55/views/1?filterQuery=file

* to help the component into the next phase we only need to have 1 implementation in OIP 
* later we will need to change ALL of the File implementations for NLDS variable token-styles

In order to bring it fully through 'Help Wanted' stage, people from all different disciplines then need to 'like' the NLDS Slack message for this first stage.

https://nl-design-system.github.io/denhaag/?path=/docs/react-file--docs
https://www.npmjs.com/package/@gemeente-denhaag/file
https://github.com/nl-design-system/denhaag/blob/main/components/File/src/index.scss
https://github.com/nl-design-system/denhaag/blob/main/proprietary/tokens/src/components/denhaag/file.tokens.json

## Issue References

Getting it. from 'Help Wanted' into the '**Community** board:
https://github.com/orgs/nl-design-system/projects/29

Also as part of the Mijn Services Community Sprint:
https://github.com/orgs/nl-design-system/projects/34/views/13

- Github Issue Open-Inwoner: https://github.com/maykinmedia/open-inwoner/issues/2220

## Checklist

- [x] CHANGELOG.rst updated
- [x] Codecov report reviewed for untested lines
- [x] Storybook component updated/created
      
- [x] Vitest tests added/updated

### CODE REVIEW

File: src/open_inwoner/react/components/File/File.tsx [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+            outlined={true}
+          />
+        )}
+      </div>
+
+      <div class="denhaag-file__right">
+        <div class="denhaag-file__label">
+          <span>{name}</span>
+          {extension && <span> ({extension}</span>}
+          {size && <span>, {size})</span>}
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: Size is shown without the value (bytes, kb, mb)

File: src/open_inwoner/react/components/File/File.tsx [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+            name={getIconName(isImage, extension)}
+            outlined={true}
+          />
+        )}
+      </div>
+
+      <div class="denhaag-file__right">
+        <div class="denhaag-file__label">
+          <span>{name}</span>
+          {extension && <span> ({extension}</span>}
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: If `extension` is not defined the ending is `, 6000)`. No starting `(`

File: src/open_inwoner/react/components/File/File.tsx [hunk 3]
```diff
@@ -0,0 +1,126 @@
...
+    'jpeg',
+    'png',
+    'gif',
+    'webp',
+    'tiff',
+    'tif',
+    'svg',
+  ];
+
+  const getIconName = (isImg?: boolean, ext?: string): string => {
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: Why pass `isImg` and`extension` if we can read if from the component props.

This should actually be a useMemo.

Comment (stefrado) [reply src/open_inwoner/react/components/File/File.tsx]: So this is just a file or img? No video for example?

File: src/open_inwoner/react/components/File/File.tsx [hunk 4]
```diff
@@ -0,0 +1,126 @@
...
+  lastUpdated?: string;
+  loading?: boolean;
+  className?: string;
+  showDownload?: boolean;
+  showDelete?: boolean;
+}
+
+type FileComponentProps = IFileProps;
+
+const File: AC<FileComponentProps> = ({
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]:
```suggestion
const File: AC<IFileProps> = ({
```

File: src/open_inwoner/react/components/File/File.tsx [hunk 5]
```diff
@@ -0,0 +1,126 @@
...
+  deleteUrl,
+  lastUpdated,
+  loading,
+  className,
+  showDownload = true,
+  showDelete,
+}) => {
+  const intl = useIntl();
+
+  const IMAGE_TYPES = [
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: This is a perfect example for an `enum` inside `File/choices.ts`

File: src/open_inwoner/react/components/File/File.tsx [hunk 6]
```diff
@@ -0,0 +1,126 @@
...
+
+  return (
+    <div class={`denhaag-file ${className || ''}`}>
+      <div class="denhaag-file__left">
+        {loading ? (
+          <span class="loading">⟳</span>
+        ) : (
+          <MaterialIcon
+            name={getIconName(isImage, extension)}
+            outlined={true}
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: outlined is true on default can be removed.

File: src/open_inwoner/react/components/File/File.tsx [hunk 7]
```diff
@@ -0,0 +1,126 @@
...
+
+      <div class="denhaag-file__right">
+        <div class="denhaag-file__label">
+          <span>{name}</span>
+          {extension && <span> ({extension}</span>}
+          {size && <span>, {size})</span>}
+          {lastUpdated && <span> — {lastUpdated}</span>}
+        </div>
+
+        {(showDelete ?? removable) && deleteUrl ? (
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: If this should be (true/false or true/false) and true/false. Then this is a better syntax. Also i do think that this `a ? b : c ? d : e` is hard to follow

```suggestion
        {(showDelete || removable) && deleteUrl ? (
```

**Review by stefrado — CHANGES_REQUESTED** [review]
I'll finish this review later...

File: src/open_inwoner/react/components/File/File.scss
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.scss:1]: Why is this suffixed with `-nlds`?

File: src/open_inwoner/react/components/File/File.tsx [hunk 8]
```diff
@@ -0,0 +1,126 @@
...
+          <button
+            class="denhaag-file__link denhaag-link--remove"
+            onClick={handleDelete(deleteUrl)}
+            type="button"
+          >
+            <MaterialIcon name="delete" outlined={true} />
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: outlined is true on default

File: src/open_inwoner/react/components/File/File.tsx [hunk 9]
```diff
@@ -0,0 +1,126 @@
...
+    defaultMessage: 'Delete',
+  });
+
+  const downloadLabel = intl.formatMessage({
+    id: 'file.download',
+    description: 'Download button label',
+    defaultMessage: 'Download',
+  });
+
+  const handleDelete = (url: string) => (e: MouseEvent) => {
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: you could just use `deleteUrl`. And change the `() => () => {}` into `() => {}`

File: src/open_inwoner/react/components/File/File.tsx [hunk 10]
```diff
@@ -0,0 +1,126 @@
...
+    if (confirm(confirmDeleteText)) {
+      window.location.href = url;
+    }
+  };
+
+  return (
+    <div class={`denhaag-file ${className || ''}`}>
+      <div class="denhaag-file__left">
+        {loading ? (
+          <span class="loading">⟳</span>
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: Why not using an icon for this?

```tsx
          <span class="loading"><SomeSPinnerIcon/></span>
```

File: src/open_inwoner/react/components/File/File.tsx [hunk 11]
```diff
@@ -0,0 +1,126 @@
...
+  const downloadLabel = intl.formatMessage({
+    id: 'file.download',
+    description: 'Download button label',
+    defaultMessage: 'Download',
+  });
+
+  const handleDelete = (url: string) => (e: MouseEvent) => {
+    e.preventDefault();
+    if (confirm(confirmDeleteText)) {
+      window.location.href = url;
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: If this should be a redirect, use `location.assign()`

File: src/open_inwoner/react/components/File/File.tsx [hunk 12]
```diff
@@ -0,0 +1,126 @@
...
+    }
+  };
+
+  return (
+    <div class={`denhaag-file ${className || ''}`}>
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: use clsx :)

File: src/open_inwoner/react/components/File/File.tsx [hunk 13]
```diff
@@ -0,0 +1,126 @@
...
+  href?: string;
+  extension?: string;
+  isImage?: boolean;
+  removable?: boolean;
+  removableLabel?: string;
+  deleteUrl?: string;
+  lastUpdated?: string;
+  loading?: boolean;
+  className?: string;
+  showDownload?: boolean;
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: Maybe add a comment that this is true on default

File: src/open_inwoner/react/components/File/File.tsx [hunk 14]
```diff
@@ -0,0 +1,126 @@
...
+  showDelete?: boolean;
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx:36]: Should this be false on default? And what is the difference in `removable` and `showDelete`? Both indicate that this file is removable

File: src/open_inwoner/react/components/File/File.tsx [hunk 15]
```diff
@@ -0,0 +1,126 @@
...
+            onClick={handleDelete(deleteUrl)}
+            type="button"
+          >
+            <MaterialIcon name="delete" outlined={true} />
+            <div>{removableLabel || deleteLabelDefault}</div>
+          </button>
+        ) : (showDownload ?? true) ? (
+          <a href={href} download={name} class="denhaag-file__link">
+            <MaterialIcon name="download" outlined={true} />
+            <div>{downloadLabel}</div>
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: Shouldn't this be a span? And can we make this conditional
```suggestion
            {downloadLabel && <span>{downloadLabel}</span>}
```

File: src/open_inwoner/react/components/File/File.tsx [hunk 16]
```diff
@@ -0,0 +1,126 @@
+import { AnyComponent as AC } from 'preact';
+import { useIntl } from 'react-intl';
+import { MaterialIcon } from '../MaterialIcon';
+import '@gemeente-denhaag/file/index.css';
+import './File-nlds.scss';
+
+export interface IFileProps {
+  name: string;
+  size?: string;
+  href?: string;
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: I think that `href` need some extra docs or change the name. I would prefer the name `downloadUrl` over `href`.

File: src/open_inwoner/react/components/File/File.tsx [hunk 17]
```diff
@@ -0,0 +1,126 @@
...
+  extension?: string;
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: Can't we parse the actual file name instead of relying on this prop

File: src/open_inwoner/react/components/File/constants.ts [hunk 18]
```diff
@@ -0,0 +1,24 @@
+import { WebComponentDefinition } from '@react/lib/web-component';
+import type { IFileProps } from './File';
+
+export const FILE_ITEM_DEFINITION: WebComponentDefinition<
+  'file-denhaag',
+  IFileProps & { filesId?: string }
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/constants.ts]: Why not add filesId to `IFileProps`?

**Review by stefrado — CHANGES_REQUESTED** [review]

File: src/open_inwoner/react/components/File/File.scss
Comment (jiromaykin) [reply src/open_inwoner/react/components/File/File.scss:1]: I did not know a better name and we already have a File.scss in our 'context' SCSS dir.

File: src/open_inwoner/react/components/File/constants.ts (hunk 18 above)
Comment (jiromaykin) [reply src/open_inwoner/react/components/File/constants.ts]: I should probably add that (and others) to a Types def. - we needed to extend the Denhaag File component for use in OIP (with our own icons and 'delete' interaction).

File: src/open_inwoner/react/components/File/File.tsx (hunk 17 above)
Comment (jiromaykin) [reply src/open_inwoner/react/components/File/File.tsx]: Yes. In future we may not need `src/open_inwoner/components/templatetags/file_tags.py` anymore, or perhaps put the web component in its linked HTML templates.

File: src/open_inwoner/react/components/File/File.tsx (hunk 14 above)
Comment (jiromaykin) [reply src/open_inwoner/react/components/File/File.tsx:36]: `showDelete` is the OIP replacement of denhaag's `removable` which they use for their own javascript, so it did not provide us with enough possibilities for our own delete button with our own delete script.

File: src/open_inwoner/react/components/File/File.tsx (hunk 3 above)
Comment (jiromaykin) [reply src/open_inwoner/react/components/File/File.tsx]: I cannot imagine users will upload videos, also I will be copying what the back-end once set as choices:
https://github.com/maykinmedia/open-inwoner/blob/455f8372622d58da9896bdb437c59377ce5edc9e/src/open_inwoner/components/templatetags/file_tags.py#L14

File: src/open_inwoner/react/components/File/File.scss
Comment (jiromaykin) [reply src/open_inwoner/react/components/File/File.scss:1]: But I've changed it.

File: src/open_inwoner/react/components/File/constants.ts (hunk 18 above)
Comment (jiromaykin) [reply src/open_inwoner/react/components/File/constants.ts]: i needed `filesId` in a different version where i was trying to turn this into a list, but this is actually really just an item. There is no file list component in NLDS yet.

File: src/open_inwoner/react/components/File/File.tsx (hunk 16 above)
Comment (jiromaykin) [reply src/open_inwoner/react/components/File/File.tsx]: This is one of the things I'd like to submit to Denhaag - it's not great for accessibility to turn this whole thing into 1 link, when it also has delete-functionality.

File: src/open_inwoner/react/components/File/choices.ts [hunk 19]
```diff
@@ -0,0 +1,14 @@
+export const IMAGE_TYPES = [
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/choices.ts]: use a `enum` :) https://www.typescriptlang.org/docs/handbook/enums.html
```suggestion
export enum IMAGE_TYPES {
```

File: src/open_inwoner/react/components/File/File.tsx [hunk 20]
```diff
@@ -0,0 +1,120 @@
...
+          >
+            <MaterialIcon name="delete" />
+            {(removableLabel || deleteLabelDefault) && (
+              <span>{removableLabel || deleteLabelDefault}</span>
+            )}
+          </button>
+        ) : (
+          <a href={downloadUrl} download={name} class="denhaag-file__link">
+            <MaterialIcon name="download" />
+            {downloadLabel && <span>{downloadLabel}</span>}
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: I just noticed that downloadLabel is always defined, we can remove this check, We also might want to use <FormattedMessage> to clean the head of this component

File: src/open_inwoner/react/components/File/File.tsx [hunk 21]
```diff
@@ -0,0 +1,120 @@
...
+          </a>
+        )}
+      </div>
+    </div>
+  );
+};
+
+export default File as AC<IFileProps>;
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: The type should already be present, if not there is an issue in the code.

```suggestion
export default File
```

File: src/open_inwoner/react/components/File/types.ts [hunk 22]
```diff
@@ -0,0 +1,16 @@
...
+  // Den Haag
+  name: string;
+  size?: string;
+  lastUpdated?: string;
+  loading?: boolean;
+  className?: string;
+  removableLabel?: string;
+
+  // OIP specific
+  downloadUrl?: string; // URL for the download link (Den Haag uses `href`)
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/types.ts]: I prefer TSDoc strings in types over inline `//` comments
This allows a visible comment when the variable is hovered
```suggestion
  /** URL for the download link (Den Haag uses `href`) */
  downloadUrl?: string; 
```

File: src/open_inwoner/react/components/File/utils.ts [hunk 23]
```diff
@@ -0,0 +1,9 @@
+/**
+ * Formats a file size in bytes to a human-readable string.
+ */
+export const formatFileSize = (size: string | number): string => {
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/utils.ts:19]: This util should have some test coverage. Also i found this snippet, which is a bit more robust:

https://www.geeksforgeeks.org/javascript/javascript-convert-bytes-to-human-readable-string/

File: CHANGELOG.rst [hunk 24]
```diff
@@ -28,6 +28,9 @@ Nieuwe features
 * [:gh:`2113`]: Diagram (chart.js) toegevoegd ten behoeve van de 'Mijn Afval' app.
 * [:gh:`2119`, :gh:`2182`, :pr:`2151`]: API-client en configuratie voor 'Mijn Afval' aangemaakt.
 * [:gh:`2157`, :gh:`2205`]: Toon het nieuwste antwoord op OpenKlant-vragen.
+* [:gh:`2192`, :pr:`2195`]: Filters voor 'Mijn Afval' geïmplementeerd.
```
Comment (stefrado) [inline CHANGELOG.rst]: I think you accidentally doubled this changelog entry. Please remove the one added by you :)

File: src/open_inwoner/react/components/File/types.ts [hunk 25]
```diff
@@ -0,0 +1,16 @@
+export interface IFileProps {
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/types.ts:1]: If this is the only type, we could add it to `File.tsx` as well :)

File: src/open_inwoner/react/components/File/index.ts [hunk 26]
```diff
@@ -0,0 +1,8 @@
+// Preact Component
+export { default as File } from './File';
+
+// Types
+export type * from './types';
+
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/index.ts:6]: Export the `enum` as well

```tsx
// Choices
export * from './choices';
```

File: src/open_inwoner/react/components/File/File.tsx [hunk 27]
```diff
@@ -0,0 +1,120 @@
...
+              {' '}
+              ({displayExtension})
+            </span>
+          )}
+          {!displayExtension && size && (
+            <span class="denhaag-file--oip__extension">
+              {' '}
+              ({formatFileSize(size)})
+            </span>
+          )}
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: This could be refactored to this (please check if this works)
```suggestion
          {(displayExtension || size) && (
            <span class="denhaag-file--oip__extension">
              {' '}
              ({displayExtension && displayExtension}{(displayExtension && size) && ", "}{size && formatFileSize(size)}
              )
            </span>
          )}
```

File: src/open_inwoner/react/components/File/File.tsx [hunk 28]
```diff
@@ -0,0 +1,120 @@
...
+          {/* Den Haag meta data */}
+          {lastUpdated && <span> — {lastUpdated}</span>}
+        </div>
+
+        {showDelete && deleteUrl ? (
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx:112]: I am not sure, but this looks invalid. It looks like if `showDelete` is `undefined` then nothing will render.

```suggestion
        {(showDelete && deleteUrl) ? (
```

File: src/open_inwoner/react/components/File/File.tsx [hunk 29]
```diff
@@ -0,0 +1,120 @@
...
+  const downloadLabel = intl.formatMessage({
+    id: 'file.download',
+    description: 'Download button label',
+    defaultMessage: 'Download',
+  });
+
+  const handleDelete = (e: MouseEvent) => {
+    e.preventDefault();
+    if (confirm(confirmDeleteText)) {
+      location.assign(deleteUrl!);
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: Please add a check for `deleteUrl` and if it is present :) 

We should avoid the usage of `variable!`

File: src/open_inwoner/react/components/File/File.tsx [hunk 30]
```diff
@@ -0,0 +1,120 @@
...
+}) => {
+  const intl = useIntl();
+
+  const displayExtension = useMemo((): string => {
+    if (extension) return extension;
+    return name?.split('.').pop()?.toLowerCase() || '';
+  }, [name, extension]);
+
+  const iconName = useMemo((): string => {
+    if (isImage === true) return 'image';
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]: We could add these `'image'` and `'insert_drive_file'` to a choice `enum` as well. This makes maintaining them easier

File: src/open_inwoner/react/components/File/File.tsx [hunk 31]
```diff
@@ -0,0 +1,120 @@
...
+    if (confirm(confirmDeleteText)) {
+      location.assign(deleteUrl!);
+    }
+  };
+
+  return (
+    <div class={clsx('denhaag-file', className)}>
+      <div class="denhaag-file__left">
+        {loading ? (
+          <MaterialIcon name="rotate_right" />
```
Comment (stefrado) [inline src/open_inwoner/react/components/File/File.tsx]:
```suggestion
          <MaterialIcon name={loading ? "rotate_right": iconName} />
```

**Review by stefrado — CHANGES_REQUESTED** [review]

File: src/open_inwoner/react/components/File/File.tsx (hunk 27 above)
Comment (jiromaykin) [reply src/open_inwoner/react/components/File/File.tsx]: Seems to work!
The formatter throws it on separate lines, but works.

File: src/open_inwoner/react/components/File/File.tsx (hunk 20 above)
Comment (jiromaykin) [reply src/open_inwoner/react/components/File/File.tsx]: Clean the head? You mean putting it inline? I'd really prefer to keep it here for consistency with the other labels.

File: src/open_inwoner/react/components/File/utils.ts (hunk 23 above)
Comment (jiromaykin) [reply src/open_inwoner/react/components/File/utils.ts:19]: I copied this a bit from our other human-readable-size vanilla JS in src/open_inwoner/js/components/form/FileInput.js which is quite a hairy thing that probably should be rewritten completely for future use with web components.

File: src/open_inwoner/react/components/File/types.ts (hunk 25 above)
Comment (jiromaykin) [reply src/open_inwoner/react/components/File/types.ts:1]: I would love to keep this separate because I am not sure how many new types should/will be added, also I wasn't sure about these, since I feel a File with 'delete' functionality could be a different type than 'download' functionality, also I found 1 implementation of this file thing at http://localhost:8000/samenwerken/choose-template/ without any Delete or Download button, which could be a third type - what do you think?

Screenshot 2026-03-17 at 10 40 20

File: src/open_inwoner/react/components/File/File.tsx (hunk 29 above)
Comment (jiromaykin) [reply src/open_inwoner/react/components/File/File.tsx]: Oops, I've also changed it to `window.location` now, hoping it's more specific.

File: src/open_inwoner/react/components/File/types.ts (hunk 25 above)
Comment (stefrado) [reply src/open_inwoner/react/components/File/types.ts:1]: I think that should be just included inside this type, since it is all the same component with slight variations.

If you place it above the File component, you can add extra docs to the types what it changes inside the component.

**Review by stefrado — APPROVED** [review]
Some CI issue, but overall looks good!
